# Generated by Django 6.0.3 on 2026-03-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(max_length=200)),
                ('certificado_medico', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('documento_adicional', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('tipo_inscripcion', models.CharField(choices=[('clase', 'Por clase'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
