# Generated by Django 6.0.3 on 2026-04-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curp',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('gym', 'curp')},
        ),
    ]
